Add temporary powerups
triszt4n/unity-project pull request #25
Opened 2021-11-15 20:22 UTC by poiuztrewq1

closes #11 

* Added *Hologram* powerup
* Added *Shield* powerup
* Added *SuperMode* powerup (shield + speed boost) 

Decided to implement a kind of payload system, where the effect of the powerup is apart from the monobehaviour that applies it to the player. This way its really straigthforward to create complex temporary powerups.

2021-11-15 21:25 UTC, triszt4n requested changes
Tök király és nice kód, fancy kis queue mutató a bal oldalt

Egy kérés: Ha jól láttam, a klón laserjei az űrhajó szárnyainak végéből jönnek ki, viszont az eredeti űrhajónak a cockpit melletti nyílásaiból jönnek a lövedékek: 
![image](https://user-images.githubusercontent.com/60111772/141855058-ff176b7b-b35f-4304-afb0-f1c8a9c0177c.png)

2021-11-15 21:25 UTC, triszt4n commented on Assets/Scripts/HologramController.cs
> +    private void shoot()
Maybe capitalize as `Shoot()`?

2021-11-16 13:59 UTC, poiuztrewq1 commented
Oké, `Shoot()` nagybetűsítve, és a lézer már nem a szárnyakból jön ki.

2021-11-16 14:55 UTC, triszt4n approved these changes

2021-11-16 15:04 UTC, merged