Add shield enemy
triszt4n/unity-project pull request #59
Opened 2021-11-25 15:20 UTC by poiuztrewq1

Shield enemy done
- Behaves lika e Bumper, going around randomly and bouncying off walls,
- Always tries to turn to player so that shield works, turning speed can be overdriven in the prefabs

Sidenote: Tried to create snake and failed. I think we have enough enemies. 

closes #40

2021-11-26 17:20 UTC, triszt4n approved these changes
Works perfectly

2021-11-26 19:33 UTC, vercibar commented
@poiuztrewq1 When i pulled the branch, GameManager's Enemy Spawner didn't have the Shielded prefab connected. Update GameScene pls

2021-11-26 19:33 UTC, vercibar requested changes
GameScene GameManager -> Shielded prefab is missing

2021-11-27 21:55 UTC, vercibar approved these changes

2021-11-27 22:03 UTC, triszt4n approved these changes

2021-11-28 10:41 UTC, merged